name = "MinCostFlow"
uuid = "62286e6e-1779-56f1-888a-1c0056788ce0"
author = ["Gord Stephen <gord.stephen@nrel.gov"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
